name: SkinBlacklister
main: me.noahvdaa.skinblacklister.bukkit.SkinBlacklisterBukkit
version: 1.1.0
author: NoahvdAa
api-version: 1.13
commands:
 skinblacklisterreload:
    description: Reload the config.
    usage: /skinblacklisterreload
    aliases: ['sblr']
permissions:
  skinblacklister.reload:
    description: Reload the plugin.
    default: op
  skinblacklister.bypass:
    description: Bypass the skin detection.
    default: false