name: SkinBlacklister
version: '${version}'
main: me.noahvdaa.skinblacklister.bukkit.SkinBlacklisterBukkit
api-version: 1.13
authors: [ NoahvdAa ]
description: Blacklist skins you don't want on your Minecraft server!
website: https://github.com/NoahvdAa/SkinBlacklister
